language: node_js
node_js:
- 16.18.1
env:
  global:
  - MATTERMOST_CHANNEL=publication
  - secure: jDXp4hj7CLPe0svqDPJxX/ETG7GGbdaEdwL3XbkSvd/aUhpOQLY6YwD6bpzdG83lvgHNJWU544SLECXDLdgm4XxDmF8/vXXcMMC64jreqevnriSikR/Pro5F7NAr0ORu67VUyuHgbDNC/g6TYXkZlT/Nc3nXwY4uTU/v1pLfJjlEFFUkN+NFnsuXHYWyfJ/+t5nCcCesTcwR6JxuaK16KEzGX8NH2o2Di9AWjRPirURxO11ntZ1RNmoB/HXR7BlWpOTW096EnA/6oo1juU30QvzWtqeFZLcaQ4WUPVJV3aFBAKJJyfY1ICMBP6BPXw7zg01wf4NlNFRDDNRDq8mfOQAK1sGiqb3lUvX2c6QecmEEQg51r3/0YuT+g8N3Gm/m2TbH+LhI952Yl7xjuHWnFMykEVzchSNpXwd//rEztijgAkGwGeLHNeyvE6uq1T5T+7Q+xdE/pEdUHPOmp9cOuvgDb0Yyt/5JvCJvN2duSTXLgTTtlWcpMiHdBahI7oAVdauUVikl/iem6IwtDaUKSW26xRP63QelUZaMmcAlKJjMg1sRzZeDpBQ6aqkot8Zc4f1AJMF+yEv/moeer7QbLZ7XPtwrPB6KhduIMpCqFydwiLWJLZoGFpBUp8IALkhjXkCFn+Cfa8Fa3l9XavwnORu/a8BQRbSESiXhWjBZqkk=
  - secure: wsPLMljIwZ/2VtJ7UrEJUpE9r5eB6K1Xi4ipRQsa8yqiAq3xJxr5af3Sx6PTswoQEXLPICyKuYB/vI6ZoQHDErRe12dB33HVQ1rnP5qrDnYAnAkq+yX6G41kIXnS3ifyGR/iAUw5ng6Fpoj2CN7eBcRLGyLpvdIvp3ZSKeHEK8ZFmNW+D4SbkguPdrtpouGaqtmQGOyx8GX9bp0iZjJG2d7hy54yrvSBkcygjfL9EFzZcdxjMyZkO1xD9ARb6/LkHbVBObz4AWCHEfVx64wHHYeICWG54xWraGoCfJzsnS33ykbxosgDti0AAISnuNgU0u9lLbuner1P0FT4QUResqZdOhakXVgbWmJDnDC21Ll1foaP3IunYpxf0GCMCLC67a4I2dY2JpfkStQ2+mBm+R8h2YRxKKqvcQzKZrpp1EAZ0SnHlHAyha3HI6xTkyIKPS3LH8RSpE1STI+GlhXl1mu2yvPUf7k2XAc362tTcRKNv80Q8+WJjafw9QjoKrFnLUofJ2N72WMwTOKV8FDmBRmbrkm6cXVFTkNPRVjwp37YOh1UQKcgFt+m3xlVkDNCaWXLivvwGWjRXONEMcSjp8yW0INRTt4xzaEed70D/9J9qNFvJh0TONxtZeHNp/rVtYsjcuzS97yQaHyzahqNnDIbiFZ4m9j1Fg0uVK2A2Eg=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
    --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
