language: node_js
node_js:
- 16.18.1
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: hXtCCntFnbJNumcQIr3XNGpA1p5kXkVcrwOnw8BdCJA8UEQCpJmCCq2t5Qo0mJrUDvycHGjLIhA6llY5hBGpqpr4VHWSYbfn7puSf1teJ0XN0IujrdcQ+MSleEXk/d8vUQoVI/hj6jwJOouQJc0SpP1qCUSRt6Twfe9VnJ83PaheEFMSI0fvtdIuiJ/cYKBRfsc5VyYS54z22dqkMX9Bh010/09qCu8OpAp81yZ+a8pMMpMtym4nSw6GkIi9U2ReAe2pcpq1hb+hfg7FqrLzRd0gWxbXbz9e8JI22Idv8YuLWtQpsqPI7O7WU9WMghpIr1JGCHNyOIcrTGYNJ9pH5eEOVcgkeIJak90qvCOV6VNmvS89oo/dJIQpBrSIbYY9AVAyjc+KlCJvF07TT7Tsgq5lDPAo7/rhc7xH8uHTsb0ayU+q10ulAHY4kcwZqntAC9rvA6AIH6mJqliklWNtROGClx/S7QprTKFuulk3la1XxHwn3vi2TqPlbE8v1qi6TPP5zqtTC03a2NbW7Lo/Nf3NeTrc94mFBsYS/qVlVk6BColZqMgUrUY0EeCaUEcAlvHpngweCnx1ltu3O2pYNaX2nDlc9Mrj6hr36veRdjRtwuIFPAXZ0aHdUMkuBARrGOIoF2YWiawrccR6OLWSrI5LzPO5Q6jaHTEqjCshH5I=
  # REGISTRY_TOKEN slug=alan editor=cozy space=cozy_ccc
  - secure: wsPLMljIwZ/2VtJ7UrEJUpE9r5eB6K1Xi4ipRQsa8yqiAq3xJxr5af3Sx6PTswoQEXLPICyKuYB/vI6ZoQHDErRe12dB33HVQ1rnP5qrDnYAnAkq+yX6G41kIXnS3ifyGR/iAUw5ng6Fpoj2CN7eBcRLGyLpvdIvp3ZSKeHEK8ZFmNW+D4SbkguPdrtpouGaqtmQGOyx8GX9bp0iZjJG2d7hy54yrvSBkcygjfL9EFzZcdxjMyZkO1xD9ARb6/LkHbVBObz4AWCHEfVx64wHHYeICWG54xWraGoCfJzsnS33ykbxosgDti0AAISnuNgU0u9lLbuner1P0FT4QUResqZdOhakXVgbWmJDnDC21Ll1foaP3IunYpxf0GCMCLC67a4I2dY2JpfkStQ2+mBm+R8h2YRxKKqvcQzKZrpp1EAZ0SnHlHAyha3HI6xTkyIKPS3LH8RSpE1STI+GlhXl1mu2yvPUf7k2XAc362tTcRKNv80Q8+WJjafw9QjoKrFnLUofJ2N72WMwTOKV8FDmBRmbrkm6cXVFTkNPRVjwp37YOh1UQKcgFt+m3xlVkDNCaWXLivvwGWjRXONEMcSjp8yW0INRTt4xzaEed70D/9J9qNFvJh0TONxtZeHNp/rVtYsjcuzS97yQaHyzahqNnDIbiFZ4m9j1Fg0uVK2A2Eg=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --space cozy_ccc
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
    --space cozy_ccc
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
