language: node_js
node_js:
- 16.20.2
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # MATTERMOST_HOOK_URL
  - secure: hXtCCntFnbJNumcQIr3XNGpA1p5kXkVcrwOnw8BdCJA8UEQCpJmCCq2t5Qo0mJrUDvycHGjLIhA6llY5hBGpqpr4VHWSYbfn7puSf1teJ0XN0IujrdcQ+MSleEXk/d8vUQoVI/hj6jwJOouQJc0SpP1qCUSRt6Twfe9VnJ83PaheEFMSI0fvtdIuiJ/cYKBRfsc5VyYS54z22dqkMX9Bh010/09qCu8OpAp81yZ+a8pMMpMtym4nSw6GkIi9U2ReAe2pcpq1hb+hfg7FqrLzRd0gWxbXbz9e8JI22Idv8YuLWtQpsqPI7O7WU9WMghpIr1JGCHNyOIcrTGYNJ9pH5eEOVcgkeIJak90qvCOV6VNmvS89oo/dJIQpBrSIbYY9AVAyjc+KlCJvF07TT7Tsgq5lDPAo7/rhc7xH8uHTsb0ayU+q10ulAHY4kcwZqntAC9rvA6AIH6mJqliklWNtROGClx/S7QprTKFuulk3la1XxHwn3vi2TqPlbE8v1qi6TPP5zqtTC03a2NbW7Lo/Nf3NeTrc94mFBsYS/qVlVk6BColZqMgUrUY0EeCaUEcAlvHpngweCnx1ltu3O2pYNaX2nDlc9Mrj6hr36veRdjRtwuIFPAXZ0aHdUMkuBARrGOIoF2YWiawrccR6OLWSrI5LzPO5Q6jaHTEqjCshH5I=
  # REGISTRY_TOKEN slug=alan editor=cozy space=default
  - secure: K2hhx+uGkcMkY+TxjvNgJeRh2exggYJfbJdMINCxSvaIvJ3qrOL8x1DWYyYJvN3CuxIb+UuQ88kcMV7t3Vl8E3LydSwVwGkksAswgp2Btp5cos9fwcOPlDZrsbeLyq2g9mg2iRjRgl1ewUYYKKsKZLoz/0JSaMrDZ5YQVUETzGiWIO6/+7kQPMI8bKZuEttbNlN6NmNmQX5cfaSJNl6nv5S8Sc9c5eyYkSX9c+rqPuOGKm/pUe9F9W+2LjfgfjQ6YWH57Fjajhr1kueweQf9qUsPBvvT5hOHE48Xaac642ZCvaNfVXNAs7JDpBxQkGaoilSHpYHz2r18oBgUSYSQ+Dv3vTMkvQPTzySIulfbPmfOj4nhaC04NkbANwiqXVF3EJ1HGBS9MAneFV+sFgCOhi/QS/ZLW4Bsy2s387gGVhrowHePYk5L04n4N/WxsbyqRmRSK/64HK3ur+fyBGhhTqx8UBJyejZ3J67sHpJ/I88PtI5P3W6ZoS25B8uYFUu1Sliyi/zIdlL4+7qVbgZhphU1mEtXLI1iUfqEWtEMjA9biqsX2BDRUEzpZJzlEBWYai5gFeVorJ98w+26gxQ1rW7NUOY4svL8is3ceeaOviU0mNt2wJJVgZPk++UTGzuT96DTMj1BiO5q65I0Gnk5xsG+jToE7P4Q6FHvFP0ipGk=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch:
    - master
    - main
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- if [[ -f /tmp/github_deploy_key ]]; then chmod 600 /tmp/github_deploy_key; fi
- if [[ -f /tmp/github_deploy_key ]]; then ssh-add /tmp/github_deploy_key; fi
after_deploy:
- rm -f /tmp/github_deploy_key
- ssh-add -D
